import React from 'react'

function Accomplishment() {
  return (
    <div className="accomplishments my-10 py-5 px-3">
      <h1 className='text-center font-bold text-lg md:text-4xl mb-4'>PROFESSIONAL ACCOMPLISHMENT AND CONTRIBUTIONS TO KNOWLEDGE</h1>
    <div className="flex flex-col items-center">
        <p className='mb-4 leading-6 text-sm '>In my initial two years at my current place of work, I completed a 16-week rotation each in the clinical units of Neurology physiotherapy, Orthopedic/Burns and Plastic physiotherapy, Geriatrics physiotherapy, Paediatrics physiotherapy, Women's health physiotherapy, Cardiopulmonary physiotherapy (which included ICU and burn intensive unit, and oncology care). Since the beginning March of 2019, I have been practicing as a Neurology-focus physiotherapist with round-the-clock in-patient responsibilities and outpatient clinical duties. Currently, I am the Team Lead for neurological physiotherapy. During Covid 19 pandemic, I was a member of the physiotherapy team at the isolation center for 6 text-sm months in Edo State, Nigeria. Thereafter, I documented my experience at the isolation center and I wrote an article on the Covid-19 Pandemic: A Physiotherapy Update in the University of Benin Teaching Hospital, Benin City, Edo State, Nigeria. This article was published in a peer review journal in the UK [Oyewumi, J.T., Ogbeivor, C., Omorotiomwan & <b>Hammed, I.A.</b> (2021)]. I am skilled in CT scans and MRI interpretations.</p>
        <p className='mb-4 leading-6 text-sm'>I have observed from my unit, especially the outpatient clinic that gait problems and handgrip weakness are the major complaints after being discharged from the inpatient stroke unit. Thus, I carried out a study to establish a structured therapeutic program to challenge these complaints. After establishing and administering the programs to patients for a few weeks, significant improvements in patients’ gait quality and handgrip strength were recorded. This study has been published in a peer review journal in Poland [<b>Hammed, A.I.</b>, Adodo, S.M., & Agwubike, E.O. (2018). Alterations in Gait Velocity and Grip Strength of Stroke Survivors Following a 12-Week Structured Therapeutic Exercise Programme. Journal of Biomedical Human Kinetics, 10, 76-80]. Moreover, to enhance the community integration of stroke survivors, I have established a health education program that could help my patients quickly re-integrate into the community. This study has been published in a peer review journal in the USA [<b>Hammed, A.I.</b> & Agwubike, E.O. (2017). Influence of Health Education Programme on Community Re-integration among Stroke Survivors. International Journal of Biomedical and Clinical Sciences, 3(3), 53-60]. Following these studies, my colleagues and I then established the determinants of return to work following a stroke. This work has also been published in a peer review journal in Serbia [Uzoh, P.C., <b>Hammed, A.I.</b>, Onyemechi, E., Obaseki, C.O., & Kubeyinje, S.O. (2020). Psychosocial parameters as determinants of return to work among stroke survivors. Exercise and Quality of Life Journal, 12(2), 23-29]. Furthermore, I am the first to develop and published cryokinetic protocols to challenge motor dysfunctions following spinal cord injury in Nigeria. The protocol is still in use in the neurosurgical unit and has substantially helped many patients with spinal cord injuries. This protocol (cryokinetics) has been published in a peer review journal in the USA [<b>Adebisi I. Hammed</b>, Elvis I. Agbonlahor, Solomon Ogbouma, Gabriel E. Arainru, S.M. Adodo & Collins Ogbeivor (2022). Effectiveness of Cryokinetics on Functional Independence of Participants with Spinal Cord Injury. Biomedical Journal of Scientific & Technical Research, 45(4), 36605-36612]</p>
        <p className='mb-4 leading-6 text-sm'>As a neurological physiotherapy specialist who has worked for about 5 years in Nigeria’s first and largest stroke unit, I have made expert contributions toward providing an evidence-based assessment of stroke, effective and efficacious interventions for patients with functional limitations and gait problems. I have showcased the state-of-the-art International Classification of Functioning, Health, and Disability framework for research and practice in stroke, Parkinson’s disease, and spinal cord injury with an emphasis on the optimization of functional independence and quality of life. With the aim of getting the body back to full function through randomized controlled trials, I have conducted many studies in neurology, particularly on stroke, spinal cord injury, and cerebral palsy. I have published more than 27 original scientific articles in peer review journals to provide evidence-based approaches for inpatient and outpatient rehabilitation of stroke, spinal cord injury, and cerebral palsy as well as the promotion of physical activity.</p>
        <p className='mb-4 leading-6 text-sm'>As an expert in physiotherapy who has knowledge in exercise physiology at advanced levels (M Sc.  and Ph. D), I believe I am in the best position to provide information on exercise testing, and prescriptions, and recommend therapeutic exercises based on scientific evidence and research in any community globally. This is because the science of exercise in physiotherapy is based on exercise physiology. Thus, being an expert in both physiotherapy and exercise physiology at the same time could be an edge over those who are either physiotherapists or exercise physiologists. I could make a lot of health advancements through what is called training the trainers, seminars, workshops, and publications that people can use and certain individuals can assess direct training and impact. Once an index is changed in any system, it has a way of cascading all over. That is, if the index of health is changed especially in the prevention and management of neurological conditions and training of some individuals on exercise testing and prescriptions, will surely result in having a higher workforce that is healthy. Also, I am prepared to continue scientific research into the development of new effective and efficacious exercise protocols to further prevent and manage neurological conditions</p>
             <p className='mb-4 leading-6 text-sm'>My contributions to good clinical skills, good interpersonal relationships, communication, training, and interest in research especially impact studies paved the way for my appointment as the Chairman of the Research, Publication, and Evidence-based Implementation Committee in January 2022 at the Department of Physiotherapy, University of Benin Teaching Hospital, Nigeria. In 2017, I was recommended by Nigeria’s Honorable Minister of Communication for the 2017 Hajj operation. The Honorable Minister attested to my good conduct and positivestrength of character. As a dedicated Muslim and practicing Physiotherapist, the Honorable Minister recommended me for the operation of the Medical Team, which would contribute in no small measure to the National Hajj Commission of Nigeria, in carrying out a smooth Hajj exercise in Nigeria and Saudi Arabia for the 2017 Hajj. Also, as an exercise physiologist and physiotherapist, I was a member of the medical team at the Edo 2020 National Sports Festival which took place in March; 2021 because of the Covid-19 pandemic. I led the team covering male and female football matches at the University of Benin Sports Complex, Edo State. With my knowledge in physiotherapy and exercise physiology, I managed many football players who sustained different injuries and then decided whether the players should return to the field. In addition, during my one-year National Youth Service Corps (NYSC), I volunteered in some community-based public health and medical programs. Tasks in these programs included participation in capacity building of health care providers in the host community’s primary and secondary health institutions, free physiotherapy consultation, and management of common musculoskeletal conditions such as osteoarthritis and health awareness campaigns on prevention of physical inactivity and promotion of a desirable lifestyle. Some of these programs received commendation certificates from the NYSC. I attended (and certified) HCPC’s joining the UK Workforce event on the 28th of February, 2023. In 2021, I was given an award of Excellence for Brilliant and Consistent High Standards of Performance in Physiotherapy and Clinical Research–Offered by the Department of Physiotherapy, University of Benin Teaching Hospital, Benin City, Edo State, Nigeria</p>
    </div>
    </div>
  )
}

export default Accomplishment