import React from 'react';

function Work() {
  return (
    <div className="work my-5 px-4" id="work">
      <h1 className="text-center font-bold text-xl md:text-4xl mb-4">Work Experience and Professional Experience</h1>
      <p className="text-gray-700 text-justify">
        Dr. Hammed did his one-year mandatory internship at the University of Benin Teaching Hospital and rotated through the eleven major postings in neurology, neurosurgery, orthopedics and trauma, geriatrics, community and sports, mental health, oncology, and general surgery, pediatrics, burns, and plastics surgery, obstetrics and gynecology, and cardiopulmonary between 2012 and 2013. He then underwent the compulsory National Youth Service Corps (NYSC) programs in Edo State, Nigeria. He served as a corps member at Irrua Specialist Teaching Hospital, Irrua, Edo State, Nigeria between 2014 to 2015. During this period, he was the physiotherapist in charge of the Orthopaedics Unit, Department of Surgery, Irrua Specialist Teaching Hospital. He also participated in some community-based public health and medical programs as a volunteer. Tasks in these programs included participation in capacity building of health care providers in primary and secondary health institutions of the host communities, free physiotherapy consultation, and management of common musculoskeletal conditions such as seronegative rheumatic diseases and health awareness campaigns on prevention of physical inactivity and promotion of a desirable lifestyle. Some of these programs received commendation certificates from the NYSC. Between 2015 and 2016, he worked as a physiotherapist at Aweni Hospital Saki, Oyo State, an organized private hospital where terms of reference were consultations and management of common diseases and acquisition of skills for management of common geriatrics, pediatric, and women’s health emergencies.

        In the initial two years of Dr. Hammed in the University of Benin Teaching Hospital, he completed a 16-week rotation each in the clinical units of Neurology, Orthopedic/Burns and Plastic, Geriatrics, Paediatrics, Women's health, Cardiopulmonary (which included ICU and burn intensive unit, and oncology care). Since the beginning of March 2019, he has been practicing as a Neurology-focus physiotherapist with round-the-clock in-patient responsibilities and outpatient clinical duties. Presently, he is the Team Lead for neurological physiotherapy. Dr. Hammed is currently a clinician, neurological physiotherapist, an exercise physiologist, a public health specialist, a health educator at the University of Benin Teaching Hospital and a clinical examiner of the undergraduate clinical students of the College of Medical Sciences, University of Benin, Benin City, Nigeria. He is also a researcher and an administrator. He is currently the Chairman of the Research, Publication, and Evidence-based Implementation Committee, Department of Physiotherapy, University of Benin Teaching Hospital, Nigeria. Dr. Hammed is also a visiting Consultant Physiotherapy at Fame Hospital, Benin City and the Medical Director, Comrel Physiotherapy Clinic, Benin City, Nigeria.

        Moreover, in 2016, Dr. Hammed attended a scientific conference on Sport Science in Health, Wellness, and Performance Enhancement organized by the Nigeria Association of Sports Science and Medicine in Collaboration with the Department of Human Kinetics and Sport Science and the Department of Physiotherapy University of Benin, Benin City, Nigeria. Also, in 2018, He had special training on Best Practices in Academic/Clinical Department Administration and Scholarship at the University of Medical Sciences, Ondo State Nigeria in Collaboration with Chicago State University, USA. Furthermore, in 2018, Dr. Hammed had a training in Occupational Therapy that was organized by the Occupational Therapist Association of Nigeria in conjunction with the Medical Rehabilitation Therapists Board of Nigeria. The training focused on Improving Clinical Competence and the Education of Medical Rehabilitation Therapists in Nigeria.  In March 2020, He equally had 5 days of international training in the Care of the Elderly (Geriatrics) at the University of Benin Teaching Hospital in collaboration with the Center of Excellence in Reproductive Health Innovation and National Postgraduate Medical College, Nigeria. This training was led by a Distinguished Professor of Medicine Matthew K. McNabney, MD Fellowship Program Director- Geriatrics and Medical Director- Hopkins Elder Plus, Johns Hopkins University, USA. More so, in July 2022, Dr. Hammed attended a scientific conference on Pain: From Knowledge to Practice, at Aminu Kano Teaching Hospital, Kano, Kano State, Nigeria.
      </p>
    </div>
  );
}

export default Work;
